name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Heroku CLI
      run: curl https://cli-assets.heroku.com/install.sh | sh

    - name: Authenticate Heroku CLI
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo $HEROKU_API_KEY

    - name: Set Heroku remote
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "pdf-noun-verb-extractor"
        heroku_email: "olatunjihammedtunde@gmail.com"

    - name: Deploy to Heroku
      run: git push heroku main --force
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Set Heroku environment variables
      run: |
        heroku config:set DEBUG=$DEBUG CONNECTION_STRING=$CONNECTION_STRING DB_NAME=$DB_NAME DJANGO_ENV=$DJANGO_ENV DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY HEROKU_API_KEY=$HEROKU_API_KEY PRODUCTION_ALLOWED_HOSTS=$PRODUCTION_ALLOWED_HOSTS -a pdf-noun-verb-extractor
      env:
        DEBUG: ${{ secrets.DEBUG }}
        CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DJANGO_ENV: ${{ secrets.DJANGO_ENV }}
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        PRODUCTION_ALLOWED_HOSTS: ${{ secrets.PRODUCTION_ALLOWED_HOSTS }}